### ISSUE TITLE
General Alpine with Mimalloc (not only for RUST)

### ISSUE THREAD

**Issue by Zabrane** [tweag/rust-alpine-mimalloc#11]
Hi @TerrorJack 

I've read your [blog post](https://www.tweag.io/blog/2023-08-10-rust-static-link-with-mimalloc/) with great interested.
Especially this part:

> This same technique can be used with Alpine’s own /usr/lib/libc.a, allowing mimalloc to function automatically with other languages such as C, C++, or Haskell.

I was wondering if you can help me create a Docker image for `Alpine` directly incorporating the change described in your post ... altering the default  `/usr/lib/libc.a` and replacing it with `mimalloc`.

This will help me use it with my C program (I'm not a Rust developer ... yet).

Many thanks

**Comment by Zabrane** [comment]
@TerrorJack 
It seems you did it already [here](https://github.com/tweag/rust-alpine-mimalloc/blob/master/build.sh#L37C1-L37C47):
```bash
for libc_path in $(find /usr -name libc.a); do
  {
```
Am i right?

**Comment by TerrorJack** [comment]
Yes.

**Comment by Zabrane** [comment]
Thanks a lot
